a = float(input('Birinchi sonni kiriting: '))
b = float(input('Ikkinchi sonni kiriting: '))
print(str(a) + ' ' + '+ ' + str(b) + ' ' + '= ' + str(a+b))
print(str(a) + ' ' + '- ' + str(b) + ' ' + '= ' + str(a-b))
print(str(a) + ' ' + '* ' + str(b) + ' ' + '= ' + str(a*b))
print(str(a) + ' ' + '/ ' + str(b) + ' ' + '= ' + str(a/b))
